### PR TITLE
Bug fix #2350

### LINKED ISSUE #2350: w2form v2.0 - Generation of the change event in the absence of a change in the field value by the user, when a user enters a value in a field, attributes value.current and value.previous have the same value
w2form v2.0 - generates a change event for 
all of its fields when displayed in the 2layout panel 
or w2popup window (perhaps in the refresh() function).
The event object has the following values
```
event.detail.value.current: ""
event.detail.value.previous: undefined
```
or 
```
event.detail.value.current: ""
event.detail.value.previous: null
```
When generating the Change event on user input in the field, attributes event.detail.value.current and event.detail.value.previous have the same value, which is also an error.

### PR DESCRIPTION
**Pull request by heady-yar**
Fix generation of the change event in the absence of a change in the field value by the user

### CODE REVIEW

**Comment by vitmalina** [comment]
I do not see where this change would actually make difference. Can you provide a use case with where the original code is not working before the changed and working after the change. Link to jsFiddle would suffice.

**Comment by heady-yar** [comment]
I had a form on w2ui v1.5 in which the Save button became active only after changing the value of some field by the user. When transferring this form to w2ui v2.0, I found that additional Change events occur that are not related to user input.
Your suggestion is to remove line 1874 from w2form.js gives an excellent result - I have already checked it. Thanks.

**Comment by vitmalina** [comment]
I thought more about it and I think it would be right things to do. Thanks for submitting it as a bug and fixing it. Can you please submit PR with just that change and I will merge it. Thank you

**Comment by heady-yar** [comment]
Okay, I'll do it.

**Pull request closed without merging**
