### PR TITLE
Add option withoutMinutes to time field.

### PR DESCRIPTION
**Pull request by MikeZhur**
For time field I need to be able to select only hour, not minutes.
I added option withoutMinutes that if set to true eliminate showing
minutes overlay.

### CODE REVIEW

**Comment by vitmalina** [comment]
If you need to select just hours, why don't you just create a drop down with hours only. Or just an input field?

**Comment by MikeZhur** [comment]
I think it would be an usefull option for time field. And I don't think in worth to create another control type for this reason.

**Comment by vitmalina** [comment]
I took a closer look and it looks good. I think, however, it would be better to rename "withoutMinutes" to "noMinutes" as it is shorter. I will do that.

Thanks for your contribution.

**Comment by vitmalina** [comment]
I also added it for datetime field.

**Pull request merged**
