### PR TITLE
Fix advanced search for list

### PR DESCRIPTION
**Pull request by AlexKovynev**
Fix advanced search for list type with one selection

### CODE REVIEW

**Comment by AlexKovynev** [comment]
Unfortunately this is only half the problem. Search happens, stored but not displayed in the search form (for a given "URL"). Value is assigned, albeit on a key, but is assigned, and then erased, can not find what the problem is.

**Comment by AlexKovynev** [comment]
I did it:) Perhaps there is a more elegant solution, but it works.

**Comment by vitmalina** [comment]
Please help me understand what exactly fix does. I see that it relates to enum and list field types and if I understand correctly, instead of only checking the id of the selected item, you added logic to check for its text too. Can you please give me a use case. As I see it, we should only search by id, not by text, and in fact you can have id and text be the same and then it will search for both.

**Comment by AlexKovynev** [comment]
Try "searches" element type "list" and in the options assign a "url" and get json. The problem is visible immediately, you have a static list without ids in demos, and its working, I need to get data from the database.

**Comment by AlexKovynev** [comment]
First commit solves the problem of finding, the second commit solves the problem of display.

**Pull request merged**
