### PR TITLE
toolbar's layout support Lateral and Portrait

### PR DESCRIPTION
**Pull request by wilesun**
1.Toolbar's layout support Lateral and Portrait
2.Layout's toolbar provide tbanchor property,its value list is left,right,top,bottom,top/bottom as Lateral,left and right as Portrait

### CODE REVIEW

**Comment by mrg2001** [comment]
Looks interesting, need to test before merging. Will review

**Comment by gamedevsam** [comment]
Long review :-P

**Comment by mrg2001** [comment]
I have looked at the source code and there are some problems with it. This pull request is unlikely to be merged. I will try to find some time to give more comments.

**Comment by aadrian** [comment]
> This pull request is unlikely to be merged.

The feature is quite useful however :) .

**Pull request closed without merging**
