### PR TITLE
Unit testing seconds for w2utils.isTime()

### PR DESCRIPTION
**Pull request by loxiw**

### CODE REVIEW

**Comment by vitmalina** [comment]
Thanks.

**Comment by loxiw** [comment]
Just to know, should we change the work to do/changelogs?

**Comment by vitmalina** [comment]
I usually put a note on change items in the comments on top of the file. Then, during the release, I will update necessary docs and release notes based on that info. It seems to be easy to maintain.

**Comment by loxiw** [comment]
Ok, won't modify it anymore then. Ty :)

**Pull request merged**
