### PR TITLE
Charts with d3.js

### PR DESCRIPTION
**Pull request by MaximPetrichuk**
Hi!
Propose add a new object to the library.

Regards, Maxim.

### CODE REVIEW

**Comment by mpf82** [comment]
I like the idea.

Btw, in the "prototype", you have declared ``this.last.g`` twice. The second one (line 41) should probably be ``g1``.

**Comment by MaximPetrichuk** [comment]
Sorry, right - should be g1.

**Comment by MaximPetrichuk** [comment]
I'm new in Githab. If changes after PR but before its adoption, it is necessary to cancel and create a new PR?

**Comment by mrg2001** [comment]
I am not 100% sure about charts, as I feel it deserves its own repository. I have worked with d3 extensively and do have some samples too. Let's give it a try and see where it will lead. Should it stay as a single w2ui.js file or be split into its own file, not sure yet.

**Comment by MaximPetrichuk** [comment]
Thank, this is my first pull request :)

**Comment by aadrian** [comment]
> I am not 100% sure about charts, as I feel it deserves its own repository.

+1 for their own repository (at least what NPM and Bower is concerned), i.e. W2UI should include only the required changes (if any) to allow charts easily, but no dependencies or charts IMHO.
*(many already use the one or the other charting library, so this extension would be useful more for **new** projects that haven't decided upon a charting lib yet)*

The Demos could include the charts too, since it makes no sense to host many different demos.

**Pull request merged**
