### PR TITLE
Fixing issue #2284

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
https://github.com/vitmalina/w2ui/issues/2284

### CODE REVIEW

**Comment by AlexKovynev** [comment]
it seems it wrong fix cause it need to be show an error on null val too cause it will a zero characters.

**Comment by gregoriopellegrino** [comment]
I'm not sure. We have two cases:

- field required and with minLength: in this case if the field is blank the user gets an error because the field is required
- field not required and with minLength: is it an error if the field is blank?

**Comment by AlexKovynev** [comment]
Maybe you are right too. So will be @vitmalina decision:)

**Comment by AlexKovynev** [comment]
@gregoriopellegrino it seems need to add val != '' too!

**Comment by gregoriopellegrino** [comment]
The bug was in the control for `minLength`. The problem occurred when `val = null`, since `this.getValue(field.field).length < field.options.minLength` returned error, as the `null` value has no `length` property.

If `val = ''`, then checking t`his.getValue(field.field).length < field.options.minLength` works correctly, no changes needed.

I am not sure about your solution with `else if`, it would be to test in case a field has `minLength`, but is not `required`.

**Comment by AlexKovynev** [comment]
@gregoriopellegrino Problem that if val == '' we have two errors but if val == null we only have first error with your code. With "else if" we have first error in both cases.

**Comment by AlexKovynev** [comment]
That why i suggest https://github.com/vitmalina/w2ui/pull/2296.
Cause with your code if val == '' we still have both errors, but not with val == null.

**Comment by AlexKovynev** [comment]
Maybe i better agree with you. BUT i rewrite my PR. Do you see the problem? 
.Null equal to ''. They both blank. So we need to ignore they both. But why? That why i vote for https://github.com/vitmalina/w2ui/pull/2296

**Comment by vitmalina** [comment]
Guys, sorry, it took me some time to review. I am closing two other PRs and let finish up this here. Thank you for considering all possible case of this issue. Here is what I think:

We need to display min length error, if
- field is not hidden
- field is not ['enum', 'list', 'combo']
- field.options.minLengh is defined and over 0
- value is null or length is less then specified

Need to consider if value is
- a number
- a boolean

I think the condition should be like this

```js
if (field.hidden !== true && field.options?.minLength > 0
   && !['enum', 'list', 'combo'].includes(field.type) // since minLength is used there for other purposes
   && (val == null || String(val).length < field.options.minLength)) {
```
If you agree, can you please do these modifications, and I will merge the change.

**Comment by AlexKovynev** [comment]
As for me i am completly agreed. It was one of mine PR. So i create new. You can merge it and close this [fix](https://github.com/vitmalina/w2ui/pull/2299)

**Comment by vitmalina** [comment]
merged a fix with different PR

**Pull request closed without merging**
