### PR TITLE
Treegrid: Little improvements (xhtml, search)

### PR DESCRIPTION
**Pull request by ceedriic**
When a children is found (search), show ancestors:

screen shot 2015-11-06 at 20 47 38

### CODE REVIEW

**Comment by vitmalina** [comment]
Thanks for your contribution. Children feature was just implemented and I knew that sort and search would not work properly. I was thinking of addressing it soon, but you beat me to it. I will test your commit and will merge within a week. Thanks.

**Comment by ceedriic** [comment]
I was happy to see the official treeGrid feature to land, so it was fun to try to make the sort/search work.
I hope that the code is not too bad...

**Comment by chalchis** [comment]
How I can apply these changes w2ui-1.4.3.js file?

**Comment by ceedriic** [comment]
chalchis: These changes don't apply to 1.4.3.
vitmalina: Have you found problems during testing?

**Comment by vitmalina** [comment]
Sorry it took me so long. Yes, it is definitely an improvement and sort/search seems to work. I did see a bug when you have some columns expanded and click on sort, it will not sort correctly. I think all expanded columns should be collapsed, then sort applied, then expanded columns expanded.

**Pull request merged**
