### PR TITLE
Added toolbar scrolling for overlapped buttons.

### PR DESCRIPTION
**Pull request by codeart1st**
I think this can be improved later. But for now a basic implementation of it.

### CODE REVIEW

**Comment by vitmalina** [comment]
I pulled your branch and tried to see how it works, but was unable. I tried to create a smaller container and no overflow buttons showed up. Then I tried to resize your toolbar and nothing working. Please provide instructions how to test it.

**Comment by codeart1st** [comment]
scrollbar

I tested it with the default demo sides in the project repo. Also I didn't have updated dist files in my pull request. You need to compile it from my repo before you can test it.

**Comment by codeart1st** [comment]
Ok also it seems that resize function in w2toolbar is only called in a w2layout environment (like in the example folder). Without this environment this solution needs a small hack I think. Something like

```
$(window).resize(function () {

   w2ui['toolbar'].resize();
});
```

**Comment by vitmalina** [comment]
I finally got it working. Visually, it looks great. I like the errors and it seems it would be quick easy to add resize call from grid.resize. However, I have a few suggestions:

1. Once overflow button appears in toolbar does not fit, only right button should appear, not both. If user scrolls right, then left button should appear.

2. I think it would be better when user clicks >> button to scroll toolbar to the next "page", basically entire width of the current toolbar (or to the max it is is less). Currently it scrolls about 10px for each click. 

I am merging it to the current master, but please consider my suggestions.

**Comment by codeart1st** [comment]
After one week of holiday I can answer now. I totally agree with both points of your improvement list. I will work on it later next week ;)

Cheers

**Comment by vitmalina** [comment]
Awesome. Thanks.

**Pull request merged**
