### PR TITLE
grid localize bug fix

### PR DESCRIPTION
**Pull request by srapillo**
This wants to be a contribute to solve grid toolbar localization issue.
To complete the fix you need to change w2utils.js (see my w2utils.js file change proposal)

### CODE REVIEW

**Comment by vitmalina** [comment]
What bug is it actually solving? I looked at the changes and do not see what difference will they make. I have made a checking earlier with toolbar localization fix.

**Comment by vitmalina** [comment]
I have provided a fix. See latest commits.

**Comment by srapillo** [comment]
The problem arises when you change the locale some time after having loaded a grid.
We have a web application supporting at least two languages.
The app starts in italian and the operator can change the current locale at run time switching to french (and viceversa).
With the master version when we set the new locale the grid, (but also the other objects) don't gets the new strings even if we destroy and reload it.
Our patch allowed the right behaviour (and your previous version of w2utils.locale() suggested us the solution). I see in your current version that you have removed also your previous code. I suppose you have a new philosofy about the localization. I'll try your new version.

**Comment by srapillo** [comment]
I tried your new code. It works but there is still a little step to do.
As you can see in the following image:
w2uigrid
The "search" button shows a wrong tooltip. This is because it is built in w2uiGrid by:
 'search'   : { type: 'html',   id: 'w2ui-search',
     html: '<div class="w2ui-icon icon-search-down w2ui-search-down" title="'+ 'Select Search Field' +'" '+
     'onclick="var obj = w2ui[$(this).parents(\'div.w2ui-grid\').attr(\'name\')]; obj.searchShowFields();">
     </div>'
},
and the <div> title is not updated in the refresh function.
Thanks in advance for your attention.

**Pull request closed without merging**
