### PR TITLE
Various fixes and changes for comming 1.5 version.

### PR DESCRIPTION
**Pull request by n3tfr34k**

### CODE REVIEW

**Comment by vitmalina** [comment]
I like some of the changes. However, I want to test some other. I will merge it within a weak. Thanks.

**Comment by n3tfr34k** [comment]
Probably I will add more commits next week ;)

**Comment by n3tfr34k** [comment]
Can I help you in some way to merge the pull request?

**Comment by vitmalina** [comment]
Sorry it took me so long. I have set down and looked closely at the changes you provided and they look very good. It feels like you have spent quite a bit of effort on this. Appreciate it.

**Pull request merged**
